name: Package-Build
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci

      - name: Lint
        run: npm run lint

  macOS-Build:
    runs-on: macos-12
    needs: Lint
    strategy:
      matrix:
        include:
          - arch: x86_64
          - arch: arm64
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20

      - name: Install deps
        run: |
          sudo -H pip install setuptools
        env:
          ARCH: ${{matrix.arch}}

      - name: Build packages without signing
        run: npm run make

      - name: Package artifacts
        run: |
          mkdir artifact-dmg
          mv out/make/*.dmg artifact-dmg/
          mkdir artifact-zip
          mv out/make/zip/darwin/${{matrix.arch}}/*.zip artifact-zip/

      - uses: actions/upload-artifact@master
        name: Upload DMG
        with:
          name: macOS .dmg (${{matrix.arch}})
          path: artifact-dmg

      - uses: actions/upload-artifact@master
        name: Upload ZIP
        with:
          name: macOS .zip (${{matrix.arch}})
          path: artifact-zip

  Linux-Build:
    runs-on: ubuntu-20.04
    needs: Lint
    strategy:
      matrix:
        include:
          - build-arch: x64
            arch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20

      - name: Install deps (amd64)
        run: |
          sudo apt-get update
          sudo apt-get install python3-distutils

      - name: Install npm_modules (amd64)
        run: |
          npm ci

      - name: Build packages without signing
        run: npm run make

      - uses: actions/upload-artifact@master
        name: Upload DEB (${{matrix.arch}})
        with:
          name: Linux DEB (${{matrix.arch}})
          path: out/make/deb/${{matrix.arch}}/*.deb

      - uses: actions/upload-artifact@master
        name: Upload Linux zip (${{matrix.arch}})
        with:
          name: Linux zip (${{matrix.arch}})
          path: out/make/zip/linux/${{matrix.arch}}/*.zip


  Windows-Build:
    runs-on: windows-2022
    needs: Lint
    strategy:
      matrix:
        include:
          - arch: x64
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20

      - name: Update node-gyp
        run: |
          npm install --global node-gyp@8.4.1
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: Build packages without signing
        run: npm run make

      - name: Package artifacts
        run: |
          mkdir artifact-portable
          mv out/make/zip/win32/${{matrix.arch}}/*.zip artifact-portable/

      - uses: actions/upload-artifact@master
        name: Upload portable build
        with:
          name: Windows portable build (${{matrix.arch}})
          path: artifact-portable